"""empty message

Revision ID: 9f2ec7f4df79
Revises: ea361a9bb149
Create Date: 2025-07-24 13:24:36.163948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f2ec7f4df79'
down_revision = 'ea361a9bb149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=250), nullable=True))
        batch_op.drop_column('subject')
        batch_op.drop_column('student')
        batch_op.drop_column('teacher')
        batch_op.drop_column('date')
        batch_op.drop_column('student2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student2', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('teacher', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
